version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - dpin-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost']
      interval: 30s
      timeout: 5s
      retries: 3

  postgres:
    image: postgres:alpine
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: post123
    volumes:
      - /data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - dpin-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 30s
      timeout: 5s
      retries: 5

networks:
  dpin-network:
    name: dpin-network
    driver: bridge
