name: Hub Service CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'apps/hub/**'
      - 'packages/**'
      - 'package.json'
      - 'bun.lockb'
      - '.github/workflows/hub.yml'
      - 'docker/production/Dockerfile.hub'
  pull_request:
    branches: [main]
    paths:
      - 'apps/hub/**'
      - 'packages/**'
      - 'package.json'
      - 'bun.lockb'
      - '.github/workflows/hub.yml'
      - 'docker/production/Dockerfile.hub'
env:
  SERVICE_NAME: hub
  DOCKERFILE_PATH: ./docker/production/Dockerfile.hub

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/dpin-${{ env.SERVICE_NAME }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/dpin-${{ env.SERVICE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to Production
        if: github.event_name != 'pull_request'
        env:
          DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        run: |
          # Setup SSH
          mkdir -p ~/.ssh
          echo "$DEPLOY_SSH_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

          # SSH and run deployment commands
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST << 'EOF'
            # Pull latest image
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/dpin-${{ env.SERVICE_NAME }}:${{ github.sha }}
            
            # Stop existing container
            docker stop dpin-${{ env.SERVICE_NAME }} || true
            docker rm dpin-${{ env.SERVICE_NAME }} || true
            
            # Start new container
            docker run -d \
              --name dpin-${{ env.SERVICE_NAME }} \
              --restart unless-stopped \
              --network dpin-network \
              -p 8081:8081 \
              -e DATABASE_URL=${{ secrets.DATABASE_URL_INTERNAL }} \
              --init \
              ${{ secrets.DOCKERHUB_USERNAME }}/dpin-${{ env.SERVICE_NAME }}:${{ github.sha }}
            
            # Cleanup old images
            docker image prune -f
          EOF
